export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const SAVE_TO_LOCALSTORE = "SAVE_TO_LOCALSTORE";
export const COMPLETE_ITEM = "COMPLETE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
export const LOAD_FROM_LOCALSTORE = "LOAD_FROM_LOCALSTORE";

